-- Restricted candidate export.
-- Contains raw comment and response text. Use only in approved HR review locations.

SELECT
    ROW_DATE,
    SITE_CODE,
    BUSINESS_UNIT,
    CATEGORY,
    PRIMARY_TEXT AS VOC_COMMENT,
    RESOLUTION AS VOC_RESPONSE,
    ADDITIONAL_COMMENTS,
    OWNER,
    OWNER_ASSIGNED,
    EMPLOYEE_NAME,
    CREATED_BY,
    DATE_RESOLVED,
    AUDIT_PRIORITY,
    AUDIT_REASON_CODES,
    FLAG_EXPLICIT_HR_COMPLIANCE,
    FLAG_PROTECTED_CLASS_REFERENCE,
    FLAG_WORKPLACE_CONDUCT,
    FLAG_SEXUAL_MISCONDUCT_OR_TOUCHING,
    FLAG_VIOLENCE_OR_SELF_HARM,
    FLAG_LABOR_RELATIONS,
    FLAG_SAFETY_EHS,
    FLAG_LEGAL_REGULATORY,
    FLAG_EXECUTIVE_ESCALATION,
    FLAG_GENERAL_EMPLOYEE_RELATIONS,
    AUDIT_RUN_TS,
    AUDIT_METHOD_VERSION
FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.VERA_VOC_BOARD_AUDIT_VW
WHERE FLAG_REVIEW_CANDIDATE
ORDER BY
    AUDIT_PRIORITY,
    ROW_DATE DESC,
    SITE_CODE;
